### ISSUE TITLE
Can't run this line of code

### ISSUE THREAD

**Issue by Superherow** [bre3760/TDOA_Localization_LEO_Sats#1]
I want to ask you some questions about this code. What does "opts = delimitedTextImportOptions('NumVariables', 4);" mean, in the function "importICRFfile.m"

**Comment by Superherow** [comment]
Is "opts=delimitedTextImportOptions" a function? I didn't find this code in the folder, can I get it?

**Comment by Superherow** [comment]
Maybe my version is too old, I update the following and try again

**Comment by Superherow** [comment]
> I want to ask you some questions about this code. What does "opts = delimitedTextImportOptions('NumVariables', 4);" mean, in the function "importICRFfile.m"

Maybe my version is too old, I'll update it and try again

**Comment by bre3760** [comment]
it's an auto generated function by Matlab, maybe my version 2021a is newer than what you have

**Comment by Superherow** [comment]
> it's an auto generated function by Matlab, maybe my version 2021a is newer than what you have

Thank you for your reply, I am downloading the latest matlab
